AllCops:
  Include:
    - rubocop-rspec
  Exclude:
    - 'spec/**/*'
    - '.idea/**/*'
    - 'sandpit/**/*'
    - 'Rakefile'
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
